name: inputzone
author: Anthony Bobenrieth
dependencies:
  browser: any
  browser_detect: '>=1.0.3 <2.0.0'
  core_elements: '>=0.4.0+6 <0.5.0'
  paper_elements: '>=0.5.0 <0.6.0'
  polymer: '>=0.15.1+5 <0.16.0'
transformers:
- polymer:
    entry_points:
    - web/index.html
    - web/template.html
    - web/unecm.html
    - web/ecmify.html
    - web/cwebp.html
    - web/dwebp.html
    - web/ffmpeg.html
- $dart2js:
    minify: true
