name: inputzone
dependencies:
  browser: any
  polymer: ">=0.15.0 <0.16.0"
  core_elements: ">=0.3.0+1 <0.4.0"
  paper_elements: ">=0.4.0 <0.5.0"
  browser_detect: ">=1.0.3 <2.0.0"
transformers:
  - polymer:
      entry_points:      
        - web/ecm.html
        - web/copy.html